oscar:
  oscar-cluster-9q15lefj:
    endpoint: https://oscar-cluster-9q15lefj.aisprint-cefriel.link
    auth_user: oscar
    auth_password: 7rz11x07qab7zbfh
    ssl_verify: true
    memory: 256Mi
    log_level: INFO
  oscar-cluster-u8g95rv1:
    endpoint: https://oscar-cluster-u8g95rv1.aisprint-cefriel.link
    auth_user: oscar
    auth_password: 9u6b9uxugvsqinsv
    ssl_verify: true
    memory: 256Mi
    log_level: INFO
default: oscar-cluster-9q15lefj
